version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ci3_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: ci3_db
    restart: always
    environment:
      MYSQL_DATABASE: infocontrol
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: ci_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data: